"""add topics and word topic_id

Revision ID: 069fab146520
Revises: 9270b2c15992
Create Date: 2026-05-20 19:27:40.083094
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '069fab146520'
down_revision = '9270b2c15992'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=True)
    op.add_column('words', sa.Column('topic_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_words_topic_id'), 'words', ['topic_id'], unique=False)
    op.create_foreign_key('fk_words_topic_id_topics', 'words', 'topics', ['topic_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_words_topic_id_topics', 'words', type_='foreignkey')
    op.drop_index(op.f('ix_words_topic_id'), table_name='words')
    op.drop_column('words', 'topic_id')
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
