"""drop transcription from words

Revision ID: 9270b2c15992
Revises: a089edafd871
Create Date: 2026-05-20 18:51:27.281984
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '9270b2c15992'
down_revision = 'a089edafd871'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'transcription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('transcription', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
